#!/bin/bash

# Make sure we are in the script directory
ScriptDIR=$(cd `dirname $0` && pwd)
if [ $ScriptDIR != $PWD ]; then
   echo "Ce script doit être executé depuis son dossier" 1>&2
   exit
fi

#On récupère le nombre de sessions actives de Yane
C=`sudo ./yane  -l | wc -l`

#On vérifie qu'aucune session n'est déjà lancée
if [ "$C" != "0" ] ; then
  echo "Une session est déjà lancée pour la fermer executez la commande:"
  echo "   STOP"
  exit

else
  sudo -u evann xhost +SI:localuser:root
  #On copie les scripts dans le dossier partagé du Docker correspondant
  cp ./scripts/yennefer ./files/yennefer/etc/scripts/init
  cp ./scripts/geralt ./files/geralt/etc/scripts/init
  cp ./scripts/eskel ./files/eskel/var/scripts/init
  cp ./scripts/vesemir ./files/vesemir/etc/scripts/init
  cp ./scripts/cintra ./files/cintra/etc/scripts/init
  cp ./scripts/vengerberg ./files/vengerberg/etc/scripts/init
  cp ./scripts/novigrad ./files/novigrad/etc/scripts/init
  cp ./scripts/calanthe ./files/calanthe/etc/scripts/init
  cp ./scripts/foltest ./files/foltest/etc/scripts/init
  cp ./scripts/adda ./files/adda/var/scripts/init
  echo 'Chargement des VM..'
  #On lance Yane
  sudo ./yane > /dev/null
  exit
fi
