#!/bin/bash
ip link set dev eth0 up
ip link set dev eth1 up

ip addr add 192.168.146.1/25 dev eth0
ip addr add 45.6.77.3/25 dev eth1

echo 1 > /proc/sys/net/ipv4/ip_forward

ip route add default via 45.6.77.1