#!/bin/bash

ip link set dev eth0 up
ip link set dev eth1 up

ip addr add 45.6.77.131/28 dev eth0
ip addr add 45.6.77.161/28 dev eth1

echo 1 > /proc/sys/net/ipv4/ip_forward

service quagga start

# ip route add 45.6.77.0/25 via 45.6.77.129 # vert gauche
# ip route add 45.6.77.176/28 via 45.6.77.162 # rouge gauche
# ip route add 45.6.77.144/28 via 45.6.77.162 # noir up
# ip route add 45.6.77.192/28 via 45.6.77.162 # vert up
# ip route add 45.6.77.208/28 via 45.6.77.162 # vert down

# DNS
echo "nameserver 45.6.77.210" > /etc/resolv.conf