#!/bin/bash

ip link set dev eth0 up
ip link set dev eth1 up

ip addr add 192.168.146.1/25 dev eth0
ip addr add 45.6.77.2/25 dev eth1

echo 1 > /proc/sys/net/ipv4/ip_forward

ip route add default via 45.6.77.1

# NAT
iptables -t nat -A POSTROUTING -o eth1 -j MASQUERADE

# Nat Seccurity
iptables -A FORWARD -i eht0 -o eth1 -j REJECT
iptables -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
iptables -A INPUT -m state --state NEW -i ! eth0 -j ACCEPT
iptables -P INPUT DROP

# Port forwarding - HTTP and HTTPS to the web server
iptables -t nat -A PREROUTING -i eth1 -p tcp --dport 80 -j DNAT --to-destination 192.168.146.2:80
iptables -t nat -A PREROUTING -i eth1 -p tcp --dport 443 -j DNAT --to-destination 192.168.146.2:443

# DHCP
touch /var/lib/dhcp/dhcpd.leases
dhcpd eth0

# DNS
echo "nameserver 45.6.77.210" > /etc/resolv.conf