#!/bin/bash

ip link set dev eth0 up
ip link set dev eth1 up

ip addr add 45.6.77.1/25 dev eth0
ip addr add 45.6.77.129/28 dev eth1

echo 1 > /proc/sys/net/ipv4/ip_forward

service quagga start

# ip route add 45.6.77.144/28 via 45.6.77.130 # noir up
# ip route add 45.6.77.176/28 via 45.6.77.130 # rouge droite
# ip route add 45.6.77.192/28 via 45.6.77.130 # vert up

# ip route add 45.6.77.160/28 via 45.6.77.131 # noir down
# ip route add 45.6.77.208/28 via 45.6.77.131 # vert down

# DNS
echo 45.6.77.210 > /etc/resolv.conf
