#!/bin/bash

ip link set dev eth0 up
ip link set dev eth1 up
ip link set dev eth2 up

ip addr add 45.6.77.146/28 dev eth0
ip addr add 45.6.77.178/28 dev eth1
ip addr add 45.6.77.193/28 dev eth2

echo 1 > /proc/sys/net/ipv4/ip_forward

service quagga start

# ip route add 45.6.77.0/25 via 45.6.77.145 # vert gauche
# ip route add 45.6.77.128/28 via 45.6.77.145 # rouge gauche
# ip route add 45.6.77.160/28 via 45.6.77.177 # noir down
# ip route add 45.6.77.208/28 via 45.6.77.177 # vert down

# DNS
echo "nameserver 45.6.77.210" > /etc/resolv.conf